### ISSUE TITLE
Intruder 에서 Poke 동작시 일부 대화가 반복되는 문제

### ISSUE THREAD

**Issue by EBSiNoah** [hssong1221/AI-CHATBOT-GAME#17]
aff_idx => aff_poke_event_idx 로 전환하면서 생긴 문제입니다

이유로는 Affection_Poke_Interaction_Path() 함수에서 affection_exp 를 이용해 계산을 하는 부분이 있는데

affection_exp 는 시작시점에 0 을 가지므로 계산 후에도 숫자에 변화가 없다

타이틀 로고 화면에서 게임화면으로 넘어갈때 호감도 경험치가 증가하는 것과 연관이 있을 것으로 추정된다.

**Comment by hssong1221** [comment]
해결
