### ISSUE TITLE
호감도 시스템 순서 문제 발생

### ISSUE THREAD

**Issue by hssong1221** [hssong1221/AI-CHATBOT-GAME#5]
intruder 부터 시작을 해야합니다 지금은 suspicious 부터 시작하는데 바꿔주세요

**Comment by EBSiNoah** [comment]
Affection_compare() 가 수정되었어요
이제 intruder 부터 시작하고, 호감도 레벨에 따라 호감도 상태가 변화하는걸 확인 할 수 있습니다
