### ISSUE TITLE
호감도 시스템 로직 문제

### ISSUE THREAD

**Issue by hssong1221** [hssong1221/AI-CHATBOT-GAME#6]
intruder suspicious 이렇게  각 단계 넘어갈 떄 affection_exp 수치를 다시 0부터 시작해야할 거 같아요
이미지 이름이 단계넘어가면 1부터 다시 시작하니까 그래요

그리고 각 단계 사이에 event도 껴있는 것도 구현 해주세요

**Comment by EBSiNoah** [comment]
호감도 레벨 변화시 affection_exp 를 0 으로 초기화 하도록 했습니다
